### ISSUE TITLE
Fragment length to rawBW files 

### ISSUE THREAD

**Issue by GFrosi** [IHEC/intgerative_analysis_chip#7]
Hi @sitag ,

I am working with the rawBW files generated by postprocess.sh script. I am using the fragment length calculated by xcor step from ENCODE-ChIP-Seq pipeline. However just the fragment length for IP samples are being calculated. The input files are not being passed to xcor step during the pipeline execution. 

I would like to know how are you obtain the fragment length for input samples to run the postprocess.sh script?  

Thanks in advance for your help.

Gabriella Frosi

**Comment by sitag** [comment]
The fragment length is only when data is SET. Otherwise we used the pair information. We use the same read length for assay and control that is reported by xor on assay when data is single end. 

As the pipeline does not run xcor on control, the only other option is a fixed value for fragment length, which is  no better/worse than using the assay xcor value. 

Keep in mind, the control bams are provided - you can make whatever bigwig you want from that

**Comment by GFrosi** [comment]
Thanks a lot for your reply!
